export const serif = "'Plus Jakarta Sans', system-ui, sans-serif";
export const sans  = "'Plus Jakarta Sans', -apple-system, sans-serif";

export const s: Record<string, any> = {
  shell: { fontFamily: "var(--font-sans)", background: "var(--c-bg)", minHeight: "100%", color: "var(--c-text)", padding: "var(--space-5)", maxWidth: 780, margin: "0 auto" },
  header: { marginBottom: 18 }, logoRow: { display: "flex", alignItems: "center", gap: 12 },
  betaBadge: { display: "inline-block", fontSize: 10.5, fontWeight: 600, color: "var(--c-text-muted)", background: "var(--c-surface-2)", border: "1px solid var(--c-border)", borderRadius: 10, padding: "2px 8px", marginTop: 4 },
  h1: { fontFamily: serif, fontSize: 23, fontWeight: 800, margin: 0, letterSpacing: "-.01em" },
  sub: { margin: "2px 0 0", fontSize: 12.5, color: "var(--c-text-muted)" },
  tabs: { display: "flex", gap: 5, marginBottom: 18, background: "var(--c-surface-2)", padding: 5, borderRadius: 12, overflowX: "auto", WebkitOverflowScrolling: "touch" },
  tab: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 5, padding: "9px 4px", border: "none", borderRadius: 9, background: "transparent", color: "var(--c-text-muted)", fontFamily: sans, fontWeight: 600, fontSize: 12, cursor: "pointer", flexShrink: 0 },
  tabActive: { background: "var(--c-surface)", color: "var(--c-primary)", fontWeight: 700, boxShadow: "0 1px 3px rgba(0,0,0,.08)" },
  planGroup: { display: "flex", flexDirection: "column", gap: 4, padding: "4px 6px 5px", border: "1px solid var(--c-border)", borderRadius: 12, background: "rgba(43,140,126,0.06)", flexShrink: 0 },
  planGroupActive: { borderColor: "var(--c-primary)" },
  planGroupLabel: { fontSize: 9, fontWeight: 800, letterSpacing: ".06em", textTransform: "uppercase", color: "var(--c-text-muted)", paddingLeft: 2 },
  // TER-330: unified Planning screen header + segmented Setup/Meals sub-toggle
  planHead:       { marginBottom: "var(--space-3)" },
  planLabel:      { fontSize: 11, fontWeight: 800, letterSpacing: ".06em", textTransform: "uppercase", color: "var(--c-primary)", margin: 0 },
  planSub:        { margin: "4px 0 0", fontSize: 12.5, color: "var(--c-text-muted)" },
  subToggle:      { display: "flex", gap: 4, background: "var(--c-surface-2)", borderRadius: 12, padding: 5, marginBottom: 18 },
  subTab:         { flex: 1, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, fontWeight: 700, fontSize: 14, padding: "10px 14px", borderRadius: 10, border: "none", background: "transparent", color: "var(--c-text-muted)", cursor: "pointer", minHeight: "var(--tap-min)" },
  subTabActive:   { background: "var(--c-surface)", color: "var(--c-primary)", boxShadow: "0 1px 3px rgba(26,58,52,.12)" },
  subBadge:       { width: 20, height: 20, borderRadius: "50%", display: "grid", placeItems: "center", fontSize: 11, fontWeight: 800, background: "var(--c-surface)", color: "var(--c-text-muted)", border: "1px solid var(--c-border)" },
  subBadgeActive: { background: "var(--c-primary)", color: "#fff", border: "1px solid var(--c-primary)" },
  // TER-330: SetupDayRow (per-day) restyle + Setup pantry card
  sdrHead:        { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" as const, marginBottom: 8 },
  sdrSkipBtn:     { display: "inline-flex", alignItems: "center", gap: 6, background: "transparent", border: "none", padding: 0, cursor: "pointer" },
  sdrCheck:       { width: 20, height: 20, borderRadius: 6, border: "2px solid", display: "grid", placeItems: "center", flexShrink: 0, transition: "background 120ms, border-color 120ms" },
  sdrSkipMsg:     { margin: "2px 0 0", fontSize: 12.5, color: "var(--c-text-muted)", fontStyle: "italic" },
  main: { paddingBottom: 40 },
  card: { background: "var(--c-surface)", borderRadius: 13, padding: 16, border: "1px solid var(--c-border)" },
  cardTitle: { fontFamily: serif, fontSize: 16.5, fontWeight: 600, margin: 0 },
  cardSub: { fontSize: 12.5, color: "var(--c-text-muted)", margin: "2px 0 0", fontWeight: 400 },
  miniLabel: { fontSize: 11, color: "var(--c-text-muted)" },
  fieldLabel: { fontSize: 11, fontWeight: 700, color: "var(--c-text-muted)", textTransform: "uppercase", letterSpacing: ".04em", display: "block", marginBottom: 5 },
  slotRow: { display: "flex", gap: 6, alignItems: "center" },
  dayBlock: { background: "var(--c-surface-2)", border: "1px solid var(--c-border)", borderRadius: 10, padding: 11 },
  dayHeadRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  dayDate: { fontFamily: serif, fontSize: 14.5, fontWeight: 600, color: "var(--c-text)" },
  fxChip: { fontSize: 11.5, fontWeight: 600, color: "var(--c-text-muted)", background: "var(--c-surface-2)", borderRadius: 14, padding: "3px 10px" },
  fxChipMuted: { fontSize: 11.5, color: "var(--c-text-muted)", fontStyle: "italic" },
  toggleRow: { display: "flex", gap: 10, alignItems: "flex-start", background: "var(--c-surface-2)", border: "1px solid var(--c-border)", borderRadius: 12, padding: 13, fontSize: 13.5, cursor: "pointer", lineHeight: 1.45 },
  collapseBtn: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", background: "transparent", border: "none", cursor: "pointer", fontSize: 14, color: "var(--c-text)", fontFamily: sans },
  input: { padding: "9px 10px", border: "1px solid var(--c-border)", borderRadius: 8, fontFamily: sans, fontSize: 13, color: "var(--c-text)", boxSizing: "border-box", background: "var(--c-surface)" },
  addBtn: { display: "inline-flex", alignItems: "center", gap: 5, background: "var(--c-surface-2)", color: "var(--c-primary)", border: "1px solid var(--c-border)", borderRadius: 8, padding: "7px 12px", fontFamily: sans, fontWeight: 700, fontSize: 12.5, cursor: "pointer" },
  primaryBtn: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: "var(--space-2)", background: "var(--c-primary)", color: "var(--c-on-primary)", border: "none", borderRadius: "var(--radius-md)", padding: "0 var(--space-4)", minHeight: "var(--tap-min)", fontFamily: "var(--font-sans)", fontWeight: 700, fontSize: "var(--t-body-size)", cursor: "pointer", boxShadow: "var(--elev-primary)" },
  ghostBtn: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: "var(--space-2)", background: "transparent", color: "var(--c-text-muted)", border: "1px solid var(--c-border)", borderRadius: "var(--radius-md)", padding: "0 var(--space-4)", minHeight: "var(--tap-min)", fontFamily: "var(--font-sans)", fontWeight: 700, fontSize: "var(--t-body-size)", cursor: "pointer" },
  iconBtn: { background: "transparent", border: "none", cursor: "pointer", padding: 5, borderRadius: 6, display: "grid", placeItems: "center" },
  signOutBtn: { background: "transparent", border: "1px solid var(--c-border)", borderRadius: 8, padding: 7, cursor: "pointer", color: "var(--c-text-muted)", display: "grid", placeItems: "center", flexShrink: 0 },
  mealCard: { background: "var(--c-surface)", borderRadius: 13, padding: 16, border: "1px solid var(--c-border)", overflow: "hidden" },
  mealTop: { marginBottom: 8 },
  slotTag: { fontSize: 11.5, fontWeight: 700, color: "var(--c-text-muted)", textTransform: "uppercase", letterSpacing: ".04em" },
  mealName: { fontFamily: serif, fontSize: 18, fontWeight: 600, margin: 0, color: "var(--c-text)" },
  mealDesc: { fontSize: 13.5, color: "var(--c-text-muted)", margin: "4px 0 0", lineHeight: 1.45 },
  cuisineTag: { display: "inline-block", fontSize: 10.5, fontWeight: 700, color: "var(--c-pill-text)", background: "var(--c-accent)", padding: "1px 7px", borderRadius: 10, marginRight: 4, textTransform: "uppercase", letterSpacing: ".03em" },
  acceptedPill: { display: "inline-flex", alignItems: "center", gap: 4, background: "var(--c-primary)", color: "var(--c-on-primary)", fontSize: 11.5, fontWeight: 700, padding: "4px 9px", borderRadius: 20, whiteSpace: "nowrap" },
  reuseNote: { display: "flex", alignItems: "center", gap: 6, background: "var(--c-warning-bg)", border: "1px solid var(--c-warning-bg)", color: "var(--c-warning)", fontSize: 12.5, padding: "7px 11px", borderRadius: 8, marginTop: 10 },
  tagWrap: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 11 },
  tag: { background: "var(--c-surface-2)", color: "var(--c-text-muted)", fontSize: 11.5, fontWeight: 600, padding: "3px 9px", borderRadius: 20, overflowWrap: "break-word", maxWidth: "100%" },
  acceptBtn: { display: "inline-flex", alignItems: "center", gap: 6, background: "var(--c-primary)", color: "var(--c-on-primary)", border: "none", borderRadius: 8, padding: "8px 15px", fontFamily: sans, fontWeight: 700, fontSize: 13, cursor: "pointer" },
  rejectBtn: { display: "inline-flex", alignItems: "center", gap: 6, background: "var(--c-surface)", color: "var(--c-danger)", border: "1px solid var(--c-danger-bg)", borderRadius: 8, padding: "8px 14px", fontFamily: sans, fontWeight: 700, fontSize: 13, cursor: "pointer" },
  thumb: { display: "grid", placeItems: "center", width: 34, height: 34, background: "var(--c-surface)", border: "1px solid", borderRadius: 8, cursor: "pointer" },
  rotateBtn: { display: "inline-flex", alignItems: "center", gap: 5, background: "var(--c-warning-bg)", color: "var(--c-warning)", border: "1px solid var(--c-warning-bg)", borderRadius: 8, padding: "7px 11px", fontFamily: sans, fontWeight: 700, fontSize: 12.5, cursor: "pointer" },
  empty: { color: "var(--c-text-muted)", fontSize: 13.5, fontStyle: "italic", margin: 0 },
  listToolbar: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16, gap: 10 },
  catTitle: { fontFamily: serif, fontSize: 15, fontWeight: 600, margin: "0 0 8px", color: "var(--c-primary)", borderBottom: "1px solid var(--c-border)", paddingBottom: 6 },
  listItem: { display: "flex", alignItems: "center", gap: 10, padding: "5px 0", fontSize: 14 },
  check: { width: 20, height: 20, borderRadius: 6, border: "1.5px solid var(--c-border)", cursor: "pointer", display: "grid", placeItems: "center", flexShrink: 0 },
  qtyText: { color: "var(--c-text-muted)", fontSize: 12.5 },
  stapleDot: { marginLeft: 6, fontSize: 10, fontWeight: 700, color: "var(--c-warning)", background: "var(--c-warning-bg)", padding: "1px 6px", borderRadius: 10 },
  pantryBtn: { fontSize: 11, fontWeight: 700, border: "1px solid", borderRadius: 14, padding: "2px 9px", cursor: "pointer" },
  starBtn: { background: "transparent", border: "none", cursor: "pointer", fontSize: 16, lineHeight: 1, padding: "0 2px", flexShrink: 0 },
  rotItem: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "var(--c-surface-2)", border: "1px solid var(--c-border)", borderRadius: 9, padding: "10px 12px" },
  timeLine: { fontSize: 12, color: "var(--c-text-muted)", margin: "8px 0 0" },
  stepsList: { margin: "10px 0 0", paddingLeft: 20, display: "grid", gap: 4 },
  stepItem: { fontSize: 13, color: "var(--c-text)", lineHeight: 1.5 },
  // Foundation type steps — PR1 tokens; consumed by PR2–PR5
  typeDisplay: { fontFamily: "var(--font-serif)", fontSize: "var(--t-display-size)", lineHeight: "var(--t-display-lh)", fontWeight: 600, letterSpacing: "-0.015em", margin: 0 },
  typeH1:      { fontFamily: "var(--font-serif)", fontSize: "var(--t-h1-size)",      lineHeight: "var(--t-h1-lh)",      fontWeight: 600, letterSpacing: "-0.01em",  margin: 0 },
  typeH2:      { fontFamily: "var(--font-serif)", fontSize: "var(--t-h2-size)",      lineHeight: "var(--t-h2-lh)",      fontWeight: 600, letterSpacing: "-0.01em",  margin: 0 },
  typeH3:      { fontFamily: "var(--font-serif)", fontSize: "var(--t-h3-size)",      lineHeight: "var(--t-h3-lh)",      fontWeight: 600,                            margin: 0 },
  typeBodyLg:  { fontFamily: "var(--font-sans)",  fontSize: "var(--t-bodylg-size)",  lineHeight: "var(--t-bodylg-lh)",  fontWeight: 400,                            margin: 0 },
  typeBody:    { fontFamily: "var(--font-sans)",  fontSize: "var(--t-body-size)",    lineHeight: "var(--t-body-lh)",    fontWeight: 400,                            margin: 0 },
  typeBodySm:  { fontFamily: "var(--font-sans)",  fontSize: "var(--t-bodysm-size)",  lineHeight: "var(--t-bodysm-lh)",  fontWeight: 400,                            margin: 0 },
  typeLabel:   { fontFamily: "var(--font-sans)",  fontSize: "var(--t-label-size)",   lineHeight: "var(--t-label-lh)",   fontWeight: 700, letterSpacing: "var(--t-label-tracking)", textTransform: "uppercase", margin: 0 },
  typeCaption: { fontFamily: "var(--font-sans)",  fontSize: "var(--t-caption-size)", lineHeight: "var(--t-caption-lh)", fontWeight: 600,                            margin: 0 },
  // TER-251: standalone RecipeCard
  rcCard:        { background: "var(--c-surface)", border: "1px solid var(--c-border)", borderRadius: "var(--radius-lg)", boxShadow: "var(--elev-1)", overflow: "hidden" },
  rcImgSlot:     { background: "var(--c-surface-2)", backgroundImage: "repeating-linear-gradient(135deg, rgba(43,140,126,.06) 0 10px, transparent 10px 20px)", display: "flex", alignItems: "center", justifyContent: "center", borderBottom: "1px solid var(--c-border)" },
  rcImgHint:     { fontFamily: "var(--font-sans)", fontSize: "var(--t-caption-size)", fontWeight: 600, color: "var(--c-text-muted)", background: "rgba(255,255,255,.65)", padding: "3px 10px", borderRadius: "var(--radius-pill)" },
  rcCuisinePill: { display: "inline-block", fontFamily: "var(--font-sans)", fontSize: "var(--t-caption-size)", fontWeight: 700, color: "var(--c-pill-text)", background: "var(--c-accent)", padding: "5px 10px", borderRadius: "var(--radius-pill)", textTransform: "uppercase" as const, letterSpacing: "0.05em" },
  rcMetaItem:    { display: "inline-flex", alignItems: "center", gap: 6, color: "var(--c-text)", fontFamily: "var(--font-sans)", fontSize: "var(--t-bodysm-size)", lineHeight: "var(--t-bodysm-lh)" },
  rcKcalBadge:   { fontFamily: "var(--font-sans)", fontSize: "var(--t-caption-size)", fontWeight: 600, color: "var(--c-primary)", background: "var(--c-surface-2)", padding: "3px 10px", borderRadius: "var(--radius-pill)" },
  rcKcalBadgeEst:{ fontFamily: "var(--font-sans)", fontSize: "var(--t-caption-size)", fontWeight: 600, color: "var(--c-warning)", background: "var(--c-warning-bg)", padding: "3px 10px", borderRadius: "var(--radius-pill)" },
  rcEffortBadge: { fontFamily: "var(--font-sans)", fontSize: "var(--t-caption-size)", fontWeight: 600, color: "var(--c-pill-text)", background: "var(--c-accent)", padding: "3px 10px", borderRadius: "var(--radius-pill)" },
  rcDivider:     { border: "none", borderTop: "1px solid var(--c-border)", margin: "var(--space-4) 0" },
  rcIngRow:      { display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: "var(--space-3)", borderBottom: "1px dashed var(--c-border)", paddingBottom: "var(--space-2)" },
  rcStaplePill:  { display: "inline-block", fontFamily: "var(--font-sans)", fontSize: "var(--t-caption-size)", fontWeight: 700, color: "var(--c-warning)", background: "var(--c-warning-bg)", padding: "2px 7px", borderRadius: "var(--radius-pill)", marginLeft: 6 },
  rcStepRow:     { display: "flex", gap: "var(--space-3)", alignItems: "flex-start" },
  rcStepMarker:  { flexShrink: 0, width: 26, height: 26, borderRadius: "var(--radius-pill)", background: "var(--c-primary-tint)", color: "var(--c-primary-hover)", display: "grid", placeItems: "center", fontFamily: "var(--font-sans)", fontWeight: 700, fontSize: "var(--t-bodysm-size)" },
  // TER-252: ListView grocery list restyle
  lvSunken:   { background: "var(--c-surface-2)", border: "1px solid var(--c-border)", borderRadius: "var(--radius-md)", padding: "var(--space-3) var(--space-4)", marginBottom: "var(--space-4)" },
  lvAhChip:   { display: "inline-flex", alignItems: "center", gap: 5, background: "var(--c-primary)", color: "var(--c-on-primary)", fontFamily: "var(--font-sans)", fontSize: "var(--t-bodysm-size)", fontWeight: 600, padding: "3px 9px 3px 10px", borderRadius: "var(--radius-pill)" },
  lvCatCard:  { background: "var(--c-surface)", borderRadius: "var(--radius-lg)", padding: "var(--space-4)", boxShadow: "var(--elev-1)", border: "1px solid var(--c-border)" },
  lvCatTitle: { fontFamily: "var(--font-serif)", fontSize: 15, fontWeight: 600, margin: "0 0 var(--space-2)", color: "var(--c-primary)", borderBottom: "1px solid var(--c-border)", paddingBottom: "var(--space-2)" },
  lvRow:      { display: "flex", alignItems: "center", gap: "var(--space-3)", minHeight: "var(--tap-min)", padding: "var(--space-1) 0" },
  lvCheck:    { width: 24, height: 24, borderRadius: "var(--radius-sm)", border: "2px solid", cursor: "pointer", display: "grid", placeItems: "center", flexShrink: 0, padding: 0, transition: "background 120ms, border-color 120ms" },
  lvHaveIt:   { fontFamily: "var(--font-sans)", fontSize: "var(--t-bodysm-size)", fontWeight: 700, border: "1px solid", borderRadius: "var(--radius-pill)", padding: "2px 9px", cursor: "pointer", whiteSpace: "nowrap" as const, display: "inline-flex", alignItems: "center", minHeight: 28 },
  lvStar:     { background: "transparent", border: "none", cursor: "pointer", padding: "0 2px", flexShrink: 0, display: "grid", placeItems: "center" },
  lvStaple:   { display: "inline-block", marginLeft: 6, fontFamily: "var(--font-sans)", fontSize: "var(--t-label-size)", fontWeight: 700, color: "var(--c-warning)", background: "var(--c-warning-bg)", padding: "2px 7px", borderRadius: "var(--radius-pill)" },
  lvFooter:   { marginTop: "var(--space-4)", padding: "var(--space-3) var(--space-4)", background: "var(--c-success-bg)", border: "1px solid var(--c-border)", borderRadius: "var(--radius-md)" },
  // TER-283: TOC wizard
  tocRow:        { background: "var(--c-surface)", border: "1px solid var(--c-border)", borderRadius: 12, overflow: "hidden" },
  tocRowActive:  { borderColor: "var(--c-primary)", boxShadow: "0 0 0 1px var(--c-primary)" },
  tocSummary:    { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 14px", background: "transparent", border: "none", cursor: "pointer", textAlign: "left" as const, gap: 12 },
  tocLeft:       { flex: 1, minWidth: 0, display: "grid", gap: 2 },
  tocDate:       { fontSize: 11, fontWeight: 700, color: "var(--c-text-muted)", textTransform: "uppercase" as const, letterSpacing: ".04em" },
  tocMealName:   { fontFamily: serif, fontSize: 15, fontWeight: 600, color: "var(--c-text)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const },
  tocDetail:     { padding: "12px 14px 14px", borderTop: "1px solid var(--c-border)" },
};
